### ISSUE TITLE
Use different output and input type parameters in Accumulate

### ISSUE THREAD

**Issue by balazsbotond** [exercism/xcsharp#160]
The current example for the Accumulate exercise has the following method signature:

```csharp
public static IEnumerable<T> Accumulate<T>(this IEnumerable<T> collection, Func<T, T> func)
```

This does not allow converting the type of sequence elements, like this:

```csharp
"1 2 3 4".Split(' ').Select(s => Convert.ToInt32(s)); // does not compile
```

Is this deliberate? If not, the method signature could be changed like this:

```csharp
public static IEnumerable<U> Accumulate<T, U>(this IEnumerable<T> collection, Func<T, U> func)
```

What do you think?

If this is not deliberately being kept simple because it is an exercise for beginners, I could send a PR with the new method signature and a unit test.

**Comment by robkeim** [comment]
Good suggestion @balazsbotond! I'm not sure this was a deliberate choice for simplicity or just done because it was the easiest thing to do.

There is no suggested data for this exercise that all of the tracks are snapping to, but most of the other tracks seem to only the same type signature as what we have currently. However, the Scala track supports cross type and has a test that explicitly verifies it:
https://github.com/exercism/xscala/blob/master/exercises/accumulate/src/test/scala/AccumulateTest.scala

Given that, I say that we should go for it. Could you please go ahead and send a PR with this update including a test that verifies a cross type function like your `Convert.ToInt32()` above?

**Comment by balazsbotond** [comment]
Great, thank you! I'm going to do it then.

**Comment by robkeim** [comment]
Looks good, thanks @balazsbotond!
