### ISSUE TITLE
Test Error in Exercise "Book Store"

### ISSUE THREAD

**Issue by cmccandless** [exercism/xcsharp#181]
The test "Basket_with_eight_books" tests for a sum value of "51.20", when the correct sum should be "51.60".

E.G: books=[1,1,2,2,3,3,4,5]
groups=[count(1,2,3,4,5),count(1,2,3)]=[5,3]
discount[5]=.75
discount[3]=.9
groups*8=[40,24]
groups*8*discount=[40*.75,24*.9]=[30,21.6]
total=30+21.6=**51.60**

This particular example also happens to be contained in the Readme for the exercise, but the arithmetic was done correctly there.

**Comment by robkeim** [comment]
@cmccandless are you talking about [this](https://github.com/exercism/x-common/blob/master/exercises/book-store/description.md) readme?

If so, the Readme calls out two different groupings for the eights books, and you need to choose the cheaper one. If you're getting 51.60 it's probably because you're using a greedy algorithm and the greedy algorithm doesn't always work in this problem :)

**Comment by robkeim** [comment]
Copying the relevant part of the readme for your convenience:

>However, a different way to group these 8 books is:
>
>1 group of 4 books --> 20% discount (1st,2nd,3rd,4th)
>+1 group of 4 books --> 20% discount (1st,2nd,3rd,5th)
>This would give a total of:
>
>4 books at a 20% discount
>+4 books at a 20% discount
>Resulting in:
>
>4 x (8 - 1.60) == 4 x 6.40 == $25.60
>+4 x (8 - 1.60) == 4 x 6.40 == $25.60
>For a total of $51.20
>
>And $51.20 is the price with the biggest discount.

**Comment by cmccandless** [comment]
Ah, that's what I get for trying to code before coffee; I misunderstood that part of the readme. My mistake.
